import Foundation

class News: ModelProtocol, WallModelProtocol {
    
    var id = 0
    var ownerId = 0
    var type: WallCellConstant.CellEnum = .unknown
    
    // header block
    var avaURL: URL?
    var name: String = ""
    var postDate: Double = 0
    var title: String = ""
    
    // media block
    var imageURLs: [URL] = []
    var videos: [Video] = []
    
    // footer block
    var likeCount = 0
    var viewCount = 0
    var messageCount = 0
    var shareCount = 0
    
    var ownOffset = 0 // generated by app
    var vkOffset = "" // returned by vk server
    var createDate = 0
    
    
    func getId() -> Int {
        id
    }
    
    func getType() -> WallCellConstant.CellEnum {
        type
    }
    
    struct Video {
        var id = 0
        var ownerId = 0
        var platform: WallCellConstant.VideoPlatform = .other
        var url: URL?
    }
}



